DVR/urls.py
# -- coding:utf-8 --
from django.conf.urls.defaults import patterns, include, url
from system.views import login,logout,index,requires_login,left,top,main
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DVR.views.home', name='home'),
    # url(r'^DVR/', include('DVR.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^login/', login),
     url(r'^logout/', logout),
     url(r'^left/', left),
     url(r'^top/', top),
     url(r'^main/', main),
     url(r'^admin/', include(admin.site.urls)),
     url(r'^index/|^$', requires_login(index)),
     
)
urlpatterns += patterns('',
#    url(r'^confirm/delete/$', uploaTestview.confirm_delete, name='confirm_delete'),
    url(r'^device/', include('device.urls')),
)
urlpatterns += patterns('',
#    url(r'^confirm/delete/$', uploaTestview.confirm_delete, name='confirm_delete'),
    url(r'^system/', include('system.urls')),
)
urlpatterns += patterns('',
#    url(r'^confirm/delete/$', uploaTestview.confirm_delete, name='confirm_delete'),
    url(r'^strategy/', include('strategy.urls')),
)
urlpatterns += patterns('',
#    url(r'^confirm/delete/$', uploaTestview.confirm_delete, name='confirm_delete'),
    url(r'^monitoring/', include('monitoring.urls')),
)

DVR/device/models.py
#--coding:utf-8--
from django.db import models
from system.models import User 

# Create your models here.
class Dtu(models.Model):
    dtu_num = models.CharField(verbose_name=u'DTU设备编号',max_length=100,unique=True)
    name = models.CharField(verbose_name=u'DTU设备名称',max_length=100)
    sim_id = models.CharField(verbose_name=u'SIM卡号',max_length=100,blank=True,unique=True)
    password = models.CharField(verbose_name=u'密码',max_length=100)
    ip_addr = models.CharField(verbose_name=u'IP地址',max_length=100)
    port = models.IntegerField(verbose_name=u'端口')
    interval = models.IntegerField(verbose_name=u'轮询时间')#轮询时间

    
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['id']

class Dtu_group(models.Model):
    name = models.CharField(verbose_name=u'DTU设备组名称',max_length=100) #组名称
    user = models.ForeignKey(User,verbose_name=u'所属用户')
    dtus = models.ManyToManyField(Dtu,through='Dtu_Group_r') 
           
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ["id"]
        unique_together = ("name", "user")
        
class Dtu_Group_r(models.Model):
    dtu = models.ForeignKey(Dtu,verbose_name=u'DTU设备')
    dtu_group = models.ForeignKey(Dtu_group,verbose_name=u'DTU设备组')
        
    def __unicode__(self):
        return  u'%s %s' % (self.dtu, self.dtu_group)
    class Meta:
        ordering = ['id']
        unique_together = ("dtu", "dtu_group")
    
        
class Dev_reg_log(models.Model):
    dtu = models.ForeignKey(Dtu,verbose_name=u'DTU设备')
    time = models.DateTimeField(verbose_name=u'DTU设备注册时间')
    status = models.BooleanField(verbose_name=u'DTU设备注册状态')
    reason = models.TextField(verbose_name=u'DTU设备注册失败原因')
    password = models.CharField(max_length=100,verbose_name=u'DTU设备提交密码')  #DTU设备上传的密码
    
    def __unicode__(self):
        return self.dtu
    class Meta:
        db_table = 'dev_reg_log'
        ordering = ['id']    



'''
车辆表,存储车辆的基本信息
'''
class Vehicle(models.Model):
    vehicle_num = models.CharField(verbose_name=u'车辆编号',max_length=100,unique=True)
    name = models.CharField(verbose_name=u'车辆名称',max_length=100)
    driver = models.CharField(verbose_name=u'联系人',max_length=100,blank=True)
    tel = models.CharField(verbose_name=u'联系方式',max_length=100,blank=True)
    descri = models.TextField(verbose_name=u'描述',blank=True,null=True)
    install_date = models.DateField(verbose_name=u'DTU设备安装日期',blank=True,null=True)
    status = models.IntegerField(verbose_name=u'DTU设备状态',blank=True,null=True)
    dtu = models.OneToOneField(Dtu,verbose_name=u'DTU设备',blank=True,null=True)  #车跟DTU设备一对一关系
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['id']
        
class Vehicle_group(models.Model):
    name = models.CharField(verbose_name=u'车辆组名称',max_length=100) #组名称
    user = models.ForeignKey(User,verbose_name=u'所属用户',)
    vehicles = models.ManyToManyField(Vehicle,through='Vehicle_Group_r')        
    def __unicode__(self):
        return self.name
    class Meta:
        ordering = ['id']
        unique_together = ("name", "user")

class Vehicle_Group_r(models.Model):
    vehicle = models.ForeignKey(Vehicle,verbose_name=u'车辆')
    vehicle_group = models.ForeignKey(Vehicle_group,verbose_name=u'车辆组')
        
    def __unicode__(self):
        return  u'%s %s' % (self.vehicle, self.vehicle_group)
    class Meta:
        ordering = ['id']
        unique_together = ("vehicle", "vehicle_group")            

DVR/device/forms.py
# --coding:utf-8--
'''
Created on 2012-7-3

@author: DTR
'''
from django import forms
from django.forms import ModelForm
from device.models import Vehicle,Dtu,Vehicle_group,Dtu_group,Vehicle_Group_r,Dtu_Group_r
from system.models import User
STATUS=((0,u'禁用'),(1,u'启用'))

class VehicleModelForm(ModelForm):
    install_date = forms.DateField(label=u'设备安装日期',widget=forms.DateInput(attrs={"onFocus":"WdatePicker()"}))
    status = forms.ChoiceField(choices=STATUS,label=u'状态')
    descri = forms.CharField(widget=forms.Textarea(attrs={'rows': "5", 'cols': "20",}))
#    vehicle_num = forms.CharField(widget=forms.TextInput(attrs={'size': 10, 'title': 'Your name',}))
    class Meta:
        model = Vehicle
#        exclude = ('install_date','status','dtu')

class UpdateVehicleForm(ModelForm):
    vehicle_num = forms.CharField(widget=forms.TextInput(attrs={'readonly': "readonly",'style':"background-color:gray"}))
    name = forms.CharField(widget=forms.TextInput(attrs={'readonly': "readonly",'style':"background-color:gray"}))
    install_date = forms.DateField(label=u'设备安装日期',required=False,widget=forms.DateInput(attrs={"onFocus":"WdatePicker()"}))
    status = forms.ChoiceField(choices=STATUS,label=u'状态',required=False)
    dtu = forms.ModelChoiceField(queryset=Dtu.objects.all(),label=u'安装的设备',required=False)
    class Meta:
        model = Vehicle
        exclude = ('driver','tel','descri')
#    install_date = models.DateField(verbose_name=u'设备安装日期',blank=True,null=True)
#    status = models.IntegerField(verbose_name=u'设备状态',blank=True,null=True)
#    device = models.OneToOneField(Dtu,verbose_name=u'设备',blank=True,null=True)          

   
class VehicleGroupModelForm(ModelForm):
    class Meta:
        model = Vehicle_group
        exclude = ('vehicles','user')
#    def save(self, commit=True):
#        if commit:
#            self.instance.save()
#        return self.instance        
class VehicleGroupRModelForm(ModelForm):
    class Meta:
        model = Vehicle_Group_r
    def __init__(self,request,*args, **kwargs):
        super(VehicleGroupRModelForm, self).__init__(*args, **kwargs)
        user = User.objects.getCurrentUser(request)
        vehicle_group = user.vehicle_group_set.all()
        self.fields['vehicle_group'].queryset = vehicle_group
#        exclude = ('user')
        
class DtuModelForm(ModelForm):
    class Meta:
        model = Dtu
        
        
class DtuGroupModelForm(ModelForm):
#    user = forms.ModelChoiceField(queryset=User.objects.get(pk=1))
    class Meta:
        model = Dtu_group
        exclude = ('dtus','user')

class DtuGroupRModeForm(ModelForm):
#    user = forms.ModelChoiceField(queryset=User.objects.get(pk=1))
    class Meta:
        model = Dtu_Group_r
    def __init__(self,request,*args, **kwargs):
        super(DtuGroupRModeForm, self).__init__(*args, **kwargs)
        user = User.objects.getCurrentUser(request)
        dtu_group = user.dtu_group_set.all()
        self.fields['dtu_group'].queryset = dtu_group

DVR/templates/car/addcar_back.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
        <div class="field">
            {{ form.vehicle_num.errors }}
            {{ form.vehicle_num.label }}
<!--            <label for="id_vehicle_num">vehicle_num:</label>-->
            {{ form.vehicle_num }}
        </div>
        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">name:</label>
            {{ form.name }}
        </div>
        <div class="field">
            {{ form.driver.errors }}
            <label for="id_driver">driver:</label>
            {{ form.driver }}
        </div>
        <div class="field">
            {{ form.tel.errors }}
            <label for="id_tel">tel:</label>
            {{ form.tel }}
        </div>
        <div class="field">
            {{ form.descri.errors }}
            <label for="id_descri">descri:</label>
            {{ form.descri }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

DVR/templates/car/group.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>车辆分组</title>
<STYLE type=text/css> 
{
	FONT-SIZE: 12px
}
.gridView {
	BORDER-RIGHT: #bad6ec 1px; BORDER-TOP: #bad6ec 1px; BORDER  -LEFT: #bad6ec 1px; COLOR: #566984; BORDER-BOTTOM: #bad6ec 1px; FONT-FAMILY: Courier New
}
.gridViewHeader {
	BORDER-RIGHT: #bad6ec 1px solid; BORDER-TOP: #bad6ec 1px solid; BACKGROUND-IMAGE: url(/static/imgs/images/bg_th.gif); BORDER-LEFT: #bad6ec 1px solid; LINE-HEIGHT: 27px; BORDER-BOTTOM: #bad6ec 1px solid
}
.gridViewItem {
	BORDER-RIGHT: #bad6ec 1px solid; BORDER-TOP: #bad6ec 1px solid; BORDER-LEFT: #bad6ec 1px solid; LINE-HEIGHT: 32px; BORDER-BOTTOM: #bad6ec 1px solid; TEXT-ALIGN: left
}
.cmdField {
	BORDER-RIGHT: 0px; BORDER-TOP: 0px; BACKGROUND-IMAGE: url(/static/imgs/bg_rectbtn.png); OVERFLOW: hidden; BORDER-LEFT: 0px; WIDTH: 67px; COLOR: #364c6d; LINE-HEIGHT: 27px; BORDER-BOTTOM: 0px; BACKGROUND-REPEAT: repeat-x; HEIGHT: 27px; BACKGROUND-COLOR: transparent; TEXT-DECORATION: none
}
.buttonBlue {
	BORDER-RIGHT: 0px; BORDER-TOP: 0px; BACKGROUND-IMAGE: url(/static/imgs/bg_button_blue.gif); BORDER-LEFT: 0px; WIDTH: 78px; COLOR: white; BORDER-BOTTOM: 0px; BACKGROUND-REPEAT: no-repeat; HEIGHT: 21px
}
</STYLE>
<META content="MSHTML 6.00.2900.5848" name=GENERATOR>
</HEAD>

<BODY 
style="BACKGROUND-POSITION-Y: -120px; BACKGROUND-IMAGE: url(/static/imgs/bg.gif); BACKGROUND-REPEAT: repeat-x">
<form name="form1" method="post" action=""> {% csrf_token %}

<DIV>

  <TABLE height="100%" cellSpacing=0 cellPadding=0 width="100%" border=0>
    <TBODY>
      <TR 
  style="BACKGROUND-IMAGE: url(/static/imgs/bg_header.gif); BACKGROUND-REPEAT: repeat-x" 
  height=47>
       <!-- <TD width="10"><SPAN 
      style="FLOAT: left; BACKGROUND-IMAGE: url(/static/imgs/main_hl.gif); WIDTH: 15px; BACKGROUND-REPEAT: no-repeat; HEIGHT: 47px"></SPAN></TD>-->
        <TD><SPAN 
      style="FLOAT: left; BACKGROUND-IMAGE: url(/static/imgs/main_hl2.gif); WIDTH: 15px; BACKGROUND-REPEAT: no-repeat; HEIGHT: 47px"></SPAN><SPAN 
      style="PADDING-RIGHT: 10px; PADDING-LEFT: 10px; FLOAT: left; BACKGROUND-IMAGE: url(/static/imgs/main_hb.gif); PADDING-BOTTOM: 10px; COLOR: white; PADDING-TOP: 10px; BACKGROUND-REPEAT: repeat-x; HEIGHT: 47px; TEXT-ALIGN: center; 0px: ">策略分组 </SPAN><SPAN 
      style="FLOAT: left; BACKGROUND-IMAGE: url(/static/imgs/main_hr.gif); WIDTH: 60px; BACKGROUND-REPEAT: no-repeat; HEIGHT: 47px"></SPAN></TD>
        <TD 
    style="BACKGROUND-POSITION: 50% bottom; BACKGROUND-IMAGE: url(file" 
    width=10></TD>
      </TR>
      <TR>
       <!-- <TD style="BACKGROUND-IMAGE: url(file">&nbsp;</TD>-->
        <TD 
    style="PADDING-RIGHT: 10px; PADDING-LEFT: 10px; PADDING-BOTTOM: 10px; COLOR: #566984; PADDING-TOP: 10px; BACKGROUND-COLOR: white" 
    vAlign=top align=middle>
          <DIV>
		  <table width="100%" align="center" border="0" cellspacing="0" cellpadding="0" style="border: 1px solid #C2E1F4;">
            <tr>
              <td align="center">组名称:&nbsp;&nbsp;
              {% if form.instance.id %}
                {{form.name}} &nbsp;&nbsp; <input type="button" id="edit" name="save" value="修改" /></td>
                <input type="hidden"  id="id" name='id' value={{form.instance.id}} />
              {% else %}
                {{form.name}} &nbsp;&nbsp; <input type="button" id="save" name="save" value="添加" /></td> 
              {% endif %}
              </tr>
          </table>
		  <br/>
		  <table align="center" border="0" width="600px"  >
				<tr>
					<td height="25" colSpan="3" >&nbsp;请选择分组&gt;&gt;</td>
	            </tr>
				<tr>
					<td width="250px" align="center">
                         
                      组名:
						<select style="width:150px" class="group"  id="groups1" onchange="getVehicleOptions(this.value,'groups1')">
						<option value ="0">未分组</option>
						{% for group in groups %}
						  <option value ="{{group.id}}">{{group}}</option>
						 {% endfor %}
						</select>
                    </td>
					<td >&nbsp;</td>
					<td width="250px"> 
                   组名:
                        <select style="width:150px" class="group"  id="groups2" onchange="getVehicleOptions(this.value,'groups2')">
                        <option value ="0">未分组</option>
                        {% for group in groups %}
                          <option value ="{{group.id}}">{{group}}</option>
                         {% endfor %}
                        </select>
                     </td>
				</tr>
				<tr>
					<td align="center" height="260"  >
					<select multiple="multiple" size="10" class="vehicles" id="vehicles1"  style="width:150px;height:200px" >
					{% for group in vehicles %}
					  <option value ="{{group.id}}">{{group}}</option>
					 {% endfor %}
					</select>
					  <br />
                  </td>
					<td align="center">
					 <input type="button" value=">>" name="button1" id="button1"/>
                     
						<br />
                        <br />
                        <br />
                        <input type="button" value="<<" name="button2" id="button2" /><br />
                        
                  </td>
				  <td align="center">
				  <select multiple="multiple" size="10" class="vehicles" id="vehicles2"  style="width:150px;height:200px" >
					{% for group in vehicles %}
					  <option value ="{{group.id}}">{{group}}</option>
					 {% endfor %}
					</select>                
				   </td>
				</tr>
				<tr>
	  </tr>
	</table>
          </DIV>
        </TD>
        <TD style="BACKGROUND-IMAGE: url(file"></TD>
      </TR>
      <TR 
  style="BACKGROUND-IMAGE: url(/static/imgs/main_fs.gif); BACKGROUND-REPEAT: repeat-x" 
  height=10>
      </TR>
    </TBODY>
  </TABLE>
</DIV>

 </form>
 
<script type="text/javascript" src="/static/js/jquery-1.3.1.js"></script>
<script type="text/javascript">
//获取要移动的车辆id
function getIDs(vehicles){
    var s ="";
    $(vehicles).find("option:selected").each(function(){
        s += $(this).val()+","
    })
    if(s!=""){
        s = s.substr(0,s.length-1);
        return s
    }else{
        alert("请选择要移动的车辆")
        return false
    }
}

function reloadVehicles(vehicleSelect,vehicles){
    // 清空下拉框
    vehicleSelect.empty()
    // 创建select选项
    $(vehicles).each(function(i){
        vehicle = vehicles[i];
        vehicleSelect.append("<option value='" + vehicle.pk + "'>" + vehicle.fields.name + "</option>" );
    })
}

$(function(){
    $("#button1,#button2").click(function(){
        button = $(this).attr("name")
         if(!$("#groups1").val()){
             alert("请选择组车辆组！");
             return false;
         }
         if (!$("#groups2").val()) {
             alert("请选择组车辆组！");
             return false;
         }
         if ($("#groups1").val() == $("#groups2").val()) {
             alert("两个组不能相同！");
             return false;
         }
         if(button=="button1"){
             ids = getIDs("#vehicles1")
         }else{
             ids = getIDs("#vehicles2")
         }
         $.post("/device/change_vehicles_group_r/", {
             groups1:$("#groups1").val(),
             groups2:$("#groups2").val(),
             ids: ids,
             button:button,
             csrfmiddlewaretoken:$("[name=csrfmiddlewaretoken]").val(),
             },function(data,textStatus){
                 var vehicles1 = data.vehicles1
                 var vehicles1Select = $("#vehicles1");
                 reloadVehicles(vehicles1Select,vehicles1);
                 
                 var vehicles2 = data.vehicles2
                 var vehicles2Select = $("#vehicles2");
                 reloadVehicles(vehicles2Select,vehicles2);
             },"json"
         );
    })
    $("#save").click(function(){
        url="/device/vehicle/group/add/"
        
        $.post(url,{
            name:$("#id_name").val(),
            csrfmiddlewaretoken:$("[name=csrfmiddlewaretoken]").val(),
        },function(data){
        	if(data=="1"){
        		alert("车辆组添加成功")
        	}else{
        		 alert("车辆组添加失败");
        	}
            location.reload();
        });
    })
    $("#edit").click(function(){
        url="/device/vehicle/group/add/"
        $.post(url,{
            name:$("#id_name").val(),
            id:$("#id").val(),
            csrfmiddlewaretoken:$("[name=csrfmiddlewaretoken]").val(),
        },function(data){
            if(data=="1"){
                alert("车辆组修改成功")
            }else{
                 alert("车辆组修改失败");
            }
            location.reload();
        });
    })
 })
function getVehicleOptions(value,groups){
        var url = "/device/vehicles/"+value+"/"
        $.getJSON(url, function(json){
            //从服务器取得的车辆集
            var vehicles = json.vehicles
            //要操作的select
            var vehicleSelect;
            if(groups=="groups1"){
                vehicleSelect = $("#vehicles1");
            }else if(groups=="groups2"){
                vehicleSelect = $("#vehicles2");
            }
            reloadVehicles(vehicleSelect,vehicles)
        });
    }
</script>
</BODY>

</HTML>

